### ISSUE TITLE
Form Validation

### ISSUE THREAD

**Issue by yauhofung** [SuperArtisMickens/TTP10-#3]
If you need help with form validation, check out the example codes from our last assignment.

###### My Contact Us Form
- https://github.com/SuperArtisMickens/TTP9-NowWithValidatedForms/blob/main/src/components/ContactUsForm.js

###### Jonathan's Example Form
- https://github.com/jonathan-chin/mec-ttp-2021-winter/blob/master/examples/form-validation/src/Controlled.js
- https://github.com/jonathan-chin/mec-ttp-2021-winter/blob/master/examples/form-validation/src/js/validators.js

**Comment by Henotis** [comment]
Thanks for form validation completion
